### ISSUE TITLE
Use CI tools, like Travis CI for testing and then merging code

### ISSUE THREAD

**Issue by karuppiah7890** [socraticorg/mathsteps#105]
Hey @evykassirer What if developers don't test code or don't add pre-commit hooks ? It's possible for new contributors, they might not see CONTRIBUTING.md or may have forgotten or something. And in that case, no one wants to commit code that fails tests. It will create issues like removing that commit and stuff. 

So I think we should use CI tools like how other great repos use them, since I see a lot of tests in mathsteps and then there are lint rules too. 

This way, no matter if the developer ran tests or not in his/her local machine, we could run the tests using CI tools before any merging.

**Comment by kevinbarabash** [comment]
CI should also run the linter as well.

**Comment by evykassirer** [comment]
yes! this would be great

I don't have admin rights - @aelnaiem can you do this, or give me admin rights for mathsteps? thanks!

**Comment by aelnaiem** [comment]
Yep, I'll look into this. Good idea :)

**Comment by aelnaiem** [comment]
Added Travis :)

**Comment by evykassirer** [comment]
reopening until we figure out how to add the linter

**Comment by kevinbarabash** [comment]
@evykassirer should be able to add a `scripts` section to .travis.yml like so:
```
script:
  - npm lint  # or whatever the command is to run the linter
  - npm test
```

**Comment by evykassirer** [comment]
yay thanks Kevin :D
