### ISSUE TITLE
Canceling out of more node types (functions)

### ISSUE THREAD

**Issue by aelnaiem** [socraticorg/mathsteps#110]
`nthRoot(2)/nthRoot(2)` should simplify to 1, similarly for abs(x)/abs(x)

**Comment by evykassirer** [comment]
I tried adding these two tests to  `cancelLikeTerms.test.js` 

- `['nthRoot(2)/nthRoot(2)', '1']`
- `['abs(x)/abs(x)', '1']`

and both passed

is this failing somewhere else @aelnaiem ?

**Comment by kevinbarabash** [comment]
Not sure where this should go, but would another test case be `['((-x)^2)/(x^2)', '1']`?

**Comment by evykassirer** [comment]
ooo yeah.

I think that'd be separate from this though. We want to handle (-x)^2 -> x^2. This is a dealing with negatives/coefficients when squaring thing, which we don't do at all i think? `(2x)^2` might not even go to `4x^2`. Let's open an issue for that

**Comment by aelnaiem** [comment]
Interesting! Let's close this and open another issue, and I'll track down why our specific implementation had this bug.
