### ISSUE TITLE
When numerator and denominator are negative, the fraction doesn't simplify

### ISSUE THREAD

**Issue by aelnaiem** [socraticorg/mathsteps#112]
e.g. -8/-32 only cancels out the negatives

**Comment by evykassirer** [comment]
I added `['-8/-32', '1/4']` as a test to `simplify.test.js` and it worked for me

output from debug:

```
Simplifying: -8/-32
CANCEL_MINUSES
8/32

SIMPLIFY_FRACTION
1/4
```

are there issues in Athena (the Socratic private code that uses this)?

or is there some other test you can find that fails
