### ISSUE TITLE
question about flattening

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#116]
question from @sangwinc (originally in #90, moved here because it wasn't specific to equations)

> Can I ask (sorry I didn't read the code....) how you are dealing with "associative, commutative binary operators" such as + and *?
> 
> Maxima has an "n-ary" operator concept which allows "+" to have an arbitrary number of arguments.
> So (x + 1) - 1 is (internally) like "+"("+"(x,1),-1) and x+1-1 is like "+"(x,1,-1).
> 
> I quite like this design. "flattening" the first example into the second is essentially using associativity.
> 
> You still have the unary minus to worry about, e.g. "+"(x,1,-1) might be displayed as x+1+-1, so that is an important detail.

**Comment by evykassirer** [comment]
Answer:

Yes! We deal with those things exactly as you describe. You can learn more in our [blog post](https://blog.socratic.org/stepping-into-math-open-sourcing-our-step-by-step-solver-9b5da066ae36#.yc5hcshjs) under the heading "2. Modifying expression trees for step-by-step solutions"

**Comment by evykassirer** [comment]
feel free to ask more followup questions about that here, or close the issue if you're satisfied :)

**Comment by tkosan** [comment]
The PRESS researchers also implemented "flattening" in their solver, and they used a data structure called a "bag" to represent variadic functions and predicates. The following passage from Dr. Bundy's writings discusses variadic functions and predicates and the bag data structure:

[http://patternmatics.org/mathsteps/tmp/press_bags.txt](http://patternmatics.org/mathsteps/tmp/press_bags.txt)

Over the past few days I have been working on an interface between MathPiper and mathsteps so some of the visualization tools in MathPiper can be used to better understand how mathsteps works. The following image is my first attempt to visualize how each step transforms an equation's expression tree during the solving process (note, this image is tall so it needs to be clicked on to enlarge it. Also, its size is 175k):

[http://patternmatics.org/mathsteps/tmp/solve_steps_with_trees.png](http://patternmatics.org/mathsteps/tmp/solve_steps_with_trees.png)

Bag-like data structures needed to be implemented in MathPiper to hold the variadic forms of the +, *, and - operators.

**Comment by evykassirer** [comment]
cool visualization!
