### ISSUE TITLE
Propose for StackExchange Community Promotion AD

### ISSUE THREAD

**Issue by t-k-** [socraticorg/mathsteps#118]
Mathsteps is awesome, I personally believe its usefulness with regarding to its potential to change math education immensely.

To spread the world, it is time to take the chance and participate in the bid for [StackExchange 2017 Community Promotion]( http://meta.math.stackexchange.com/questions/25812/community-promotion-ads-2017). The invitation post has just been posted for several hours, Mathsteps comes into my mind so I am here to ask if anyone wants to post a Mathsteps AD on that thread. People on Math StackExchange will get the opportunity to know Mathsteps if it is selected.

**Comment by evykassirer** [comment]
thank you so much for bringing this to attention!

I'll make an ad this weekend :)

**Comment by evykassirer** [comment]
draft:

<img width="300" alt="mathsteps-ad" src="https://cloud.githubusercontent.com/assets/5634097/22621894/43e2d070-eafc-11e6-93c1-a9f10c2cc861.png">

**Comment by kevinbarabash** [comment]
Love the blueberries... but why blueberries?

**Comment by evykassirer** [comment]
I was thinking of making it part of the logo for mathsteps, because it has a lot of personal meaning to me in my internship at Socratic and in the birth of mathsteps

the math card on the Socratic app that shows step by step results is blueberry themed

also I brought blueberry yogurt into the office at Socratic (the best flavour) and on my last day of work became the blueberry queen 

![evygif_360](https://cloud.githubusercontent.com/assets/5634097/22622852/e278f77e-eb14-11e6-82aa-6f6160111a57.gif)

so I thought it'd be fun to add as the official symbol of mathsteps ^_^ and we're gonna print some stickers with the logo and mail 'em out to contributors soon!!

**Comment by t-k-** [comment]
Looks great. But I do not know whether your background is considered as "partially white", if so, you need to surround it with a 2px border:

> If the background of the image is white or partially white, there must be a 1px border (2px if high DPI) surrounding it.

I am not 100% sure about this particular requirement. But adding a border ensures your image meet the requirement.

**Comment by evykassirer** [comment]
Thanks!

Hmm true... but I think that Geogebra's grey border is _lighter_ than the blue edges of ours, so should be ok? I have a feeling"partially white" means that there's white on the edge somewhere, there needs to be a border

**Comment by t-k-** [comment]
@evykassirer NP. Then go and post your AD soon such that mathsteps will have more time to attract votes.

Good luck!

**Comment by evykassirer** [comment]
I'd appreciate it you could post is, as I don't use stack exchange and don't have the reputation :)

I was thinking of this:

[![mathsteps](http://imgur.com/0AWckKY.png)](http://github.com/socraticorg/mathsteps)


```
[![mathsteps][1]][2]

   [1]: http://imgur.com/0AWckKY.png
   [2]: http://github.com/socraticorg/mathsteps
```

**Comment by t-k-** [comment]
Sure thing. Yet when I paste your draft content, Stackexchange prompts me:

> Community ads must have an image hosted at i.stack.imgur.com; use the image button from the editor to upload.

So it seems your `http://imgur.com/0AWckKY.png` URL is not acceptable. Try to use StackExchange editor button to upload the image instead. 

Unfortunately, my working environment does not allow me to upload an image. If you want to post it soon, upload the image, get the required image URL and then ping me again.

**Comment by t-k-** [comment]
Since I am at home now, I have posted your AD just now. So ignore my previous comment.

Please notice, I have also changed your `http://github.com/socraticorg/mathsteps` link to `https://socratic.org/` because I assume most people on Math StackExchange are not familiar with GitHub. Ping me if you want to change it back.

**Comment by evykassirer** [comment]
thank you!

if they're not familiar with github, how are you hoping they'll use or contribute to it? are you hoping to advertise the app instead? maybe I should make a different ad if that's the goal

**Comment by t-k-** [comment]
The majority are not familiar with GitHub does not mean there is no hope to see people from Math StackExchange who know how to program to join the development.  As you said, the primary goal is to advertise indeed.

Sorry I change that not according to your wish. I am going to revert that link so that at least people will feel a sense of relevance. If you get an new AD image, ping me and I will change it.

But I do not consider it a big problem to link to your Github repo, after all, there is still potential to attract "developers on MSE" to contribute.

**Comment by t-k-** [comment]
I know it is a bit of frustrating to see people's downvote, but [my first attempt](http://meta.math.stackexchange.com/questions/22419/community-promotion-ads-2016) does not go well at first also. I believe if we leave a comment to ask what other users on MSE think about your AD and improve accordingly, it will eventually attract a lot of votes. After all mathsteps look quite promising overall.

**Comment by evykassirer** [comment]
I think aiming to attract mathy programmers is probably my goal (assuming they're a big enough portion of the math exchange audience)

Thanks :)

**Comment by evykassirer** [comment]
I need reputation to comment, but I'd appreciate if you could ask!

**Comment by t-k-** [comment]
Sure thing.
