### ISSUE TITLE
multiply fractions with parenthesis

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#137]
the `multiplyFractions` function doesn't handle cases like this where a fraction is in parenthesis:

- `(2 / x) * x` -> `2x / x`
- `(2 / (4x)) * 4x` -> `(2 * 4x)/4x` 

this makes it harder for things to cancel, which means that we can't get #88 working

this would be very helpful to get done soon and I don't think it's too much work 😸

**Comment by evykassirer** [comment]
another possibility is just getting rid of those parenthesis in `removeUnnecessaryParentheses` because I don't think they're needed around a fraction

**Comment by ldworkin** [comment]
Fixed by https://github.com/socraticorg/mathsteps/commit/344d15b5d5e25251cef7d6976d6a73df16661d7d
