### ISSUE TITLE
multiply fractions edge case to support cancelling

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#139]
there are some cases where we don't want to multiply fractions with other things, one of them is ` 9/2 * x  -> 9x / 2` (since this doesn't change anything and could be considered less readable)

a case we're not handling with the current logic, that *should* multiply is:

`x * 6/x -> (x * 6) / x` (which is needed for cancelling out)

one solution is just to have better cancelling code that doesn't only work with the fraction `6x/x`, and can recognize that `x` cancels with the denominator in `6/x`

another (possibly easier for now) solution would be to add a case for multiplying a symbol times a term with a symbol in the denominator

... this is a bit messy, so I'm not sure what the best solution is - open to suggestions!

this came up because of a case in #88

**Comment by kevinbarabash** [comment]
my vote would be for better canceling code.

**Comment by aelnaiem** [comment]
I agree with @kevinbarabash, let's improve the canceling code so it handles this case

**Comment by evykassirer** [comment]
I'd love for that to happen :) just haven't had the time to figure out the best way for that to work

**Comment by ldworkin** [comment]
Fixed by https://github.com/socraticorg/mathsteps/commit/344d15b5d5e25251cef7d6976d6a73df16661d7d
