### ISSUE TITLE
Typo in project description

### ISSUE THREAD

**Issue by faheel** [socraticorg/mathsteps#141]
> Step by steps ...

should be
> Step by step ...

**Comment by kevinbarabash** [comment]
🎵 day by day 🎵

**Comment by evykassirer** [comment]
Thanks!!

Sadly I don't have permission to change this :(

@aelnaiem can you either up my permissions or fix the typo? Thanks :D

**Comment by hmaurer** [comment]
@evykassirer @aelnaiem How is this going? The list of opened issues is growing; let's try to close some up :-)

**Comment by evykassirer** [comment]
ah, ahmed fixed it - great!
