### ISSUE TITLE
use exceptions for exception cases

### ISSUE THREAD

**Issue by kevinbarabash** [socraticorg/mathsteps#145]
`PolynomialTerm.isPolynomialTerm` uses the fact that the `PolynomialTerm` constructor throws if the node passed isn't a polynomial term.  `isPolynomialTerm` should contain logic to do the check without throwing and `PolynomialTerm` should call that function and throw.  This will improve the debugging situation.  Currently, breaking on all exceptions produces a lot of false positives.

**Comment by evykassirer** [comment]
agreed! that logic is pretty weird

thanks for pointing it out :)

**Comment by evykassirer** [comment]
I think the reason I did this is that they pretty much share all the same logic, which results in a lot of code duplication. Do you think it's worth that code duplication to raise errors in the logical places?

**Comment by kevinbarabash** [comment]
After looking at it more careful, I'm not sure how not duplicate logic without the try-catch.  It's probably best not to duplicate the logic.
