### ISSUE TITLE
Add a function for printing equations in LaTeX

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#160]
We can print equations to asciimath, but there's no one function call for LaTeX.

It would live in https://github.com/socraticorg/mathsteps/blob/master/lib/equation/Equation.js below `print` and look like:

`this.leftNode.toTex() + this.comparator + this.rightNode.toTex()`

**Comment by elu00** [comment]
If we particularly wanted to, there is an [npm module](https://www.npmjs.com/package/asciimath-to-latex) just for conversion between the two.

**Comment by evykassirer** [comment]
Ah, cool find!

MathJS's toTex function is probably most accurate for printing the tree exactly as it is, and since it's a one line addition I'd rather use it :)

**Comment by elu00** [comment]
Oh alright, that's probably simpler than lol.

**Comment by physedo** [comment]
@evykassirer 

> We

 can print equations to asciimath, but there's no one function call for LaTeX.

It would live in https://github.com/socraticorg/mathsteps/blob/master/lib/equation/Equation.js below print and look like:

this.leftNode.toTex() + this.comparator + this.rightNode.toTex()

> 
where below print?

**Comment by evykassirer** [comment]
I think I was talking about line 16 https://github.com/socraticorg/mathsteps/blob/master/lib/equation/Equation.js#L16

**Comment by physedo** [comment]
I can't make it work @evykassirer

**Comment by evykassirer** [comment]
can you give me a bit more details with what's going wrong? What have you tried and what isn't working?

 I'll see what I can do to help

**Comment by SirFurness** [comment]
Just writing to let someone know that I'd like to work on this.

**Comment by SirFurness** [comment]
I wrote some tests for it, but I'm not sure if I did them correctly. I'll send in the PR.

**Comment by evykassirer** [comment]
great @SirFurness ! Thanks so much for your interest and for getting involved :D

@physedo was already working on this though and very recently (just yesterday). I'd like to give people already working on things priority.

I'll give them another 5 days to let us know if they still want to work on this, and if they don't respond then it's all yours! (and I'll look at your PR at that point). How's that sound?

**Comment by evykassirer** [comment]
Also if you'd like to jump on something else feel free to take a look around open issues or chat with me about a refactoring thing we're gonna start again on soon :)

**Comment by SirFurness** [comment]
Sounds great! It's my fault for just going for it, but I enjoyed doing it anyway so it's all good.

**Comment by physedo** [comment]
You can take this @Sirfurness

**Comment by physedo** [comment]
Is it working now @SirFurness

**Comment by SirFurness** [comment]
Yep, it's working

**Comment by evykassirer** [comment]
yay ok! glad you enjoyed it :) will take a look at the PR soon - am at a conference this week so it might take a few days
