### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by nitin42** [socraticorg/mathsteps#166]
If we minify the mathsteps `lib` using **UglifyJs2** it gives build error because UglifyJs2 doesn't support ES6 (not totally sure). Considering the browser support for the ES6 build, we need to transpile ES6 to ES5 (using Babel or [Buble](buble.surge.sh)). Tracked at [mishoo/UglifyJS2#448](https://github.com/mishoo/UglifyJS2/issues/448)

**Comment by evykassirer** [comment]
Oo good to know. I don't have much experience with node -> browser code, but I guess we need it for our demo. I'm feeling pretty sick today but ll take a look into this in the next couple days

Thanks for bringing it up :)

**Comment by nitin42** [comment]
Can I look into this further ? Like adding browser support, providing UMD build and configuring Babel.

**Comment by evykassirer** [comment]
Yeah go for it! I just can't finalize anything rn cause I'm pretty busy but your research definitely helps :)

**Comment by evykassirer** [comment]
And I should be able to get back to ya next week if not earlier :)

**Comment by nitin42** [comment]
I think we can add Babel to our project. Let me know what you think!

**Comment by evykassirer** [comment]
I'm pretty sure we'll be adding babel as part of the rule porting, but I don't want to change anything on `master` for the next couple weeks while that process is happening. @aliang8 can you confirm? I remember you being interested in adding Babel for something or other (I don't know that much about it)

**Comment by nitin42** [comment]
@evykassirer Is there anything I can work on (I've two weeks before my college starts) ? Let me know!

**Comment by aliang8** [comment]
Hey @nitin42! Thanks for asking! We should set up Babel to support ES6 syntax. Would you mind taking that on?

**Comment by evykassirer** [comment]
Setting up a polished demo would also be awesome

**Comment by nitin42** [comment]
Ok! I am designing the site right now and will share the link soon. @aliang8 👍

**Comment by nitin42** [comment]
Woaah!! Seems like we won't need to configure Babel for the project. We will provide production ready `umd` build which will be supported both on the web and node environment. I'll send a PR soon !
