### ISSUE TITLE
Not dividing fractions

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#215]
Gonna put this in an issue since I think it's interesting and it'd be nice to refer to this if more people ask

@Ephs05msm said:

> While using this code on another project I came across the following scenario that confused me. I added it to the test suite on my local branch and got the same result:
>
> ![capture2](https://user-images.githubusercontent.com/9663425/28688093-b1b09afa-72de-11e7-9427-c709fabb1d95.PNG)
> ![capture](https://user-images.githubusercontent.com/9663425/28688092-b1ac9b9e-72de-11e7-9815-d775a97819c5.PNG)
>
> Same result on `master` as well (using `['x = 100 + (25^2 / 4)', 'x = 256.25']`).
>
> Is it by design that MathSteps won't simplify fractions that could be expressed as a float but not an (unrounded) integer?

**Comment by evykassirer** [comment]
my answer:

ooo that seems familiar but I'd have to go code hunting to be sure

I think the reason it's there is that in general we don't want to divide fractions midway through simplification (unless they're integers) because then you get like 5/3 x - 2/3 x turning into decimal subtraction which isn't what people usually want to see. I could see us adding a last step at the very end to divide the fraction but honestly I think people tend to prefer fractions over decimals anyways. It'd be neat to be able to show both the fraction and decimal at the end (I think cymath does this) but not sure how to fit that into how the code currently works, since we don't really let there be two answers right now

good question!

**Comment by evykassirer** [comment]
feel free to ask any followup questions here :)

if this answer makes sense and you don't have followup questions, feel free to close this issue!

**Comment by Ephs05msm** [comment]
Thanks for the explanation; makes sense! I can add a step on my end to get to a float when needed. I don't seem to be able to close this but please go ahead.

**Comment by evykassirer** [comment]
maybe we can add an option to show answers as fractions vs decimals once we have some sort of "provide options when solving" thing set up
