### ISSUE TITLE
mathsteps in a project, err when --minifyjs

### ISSUE THREAD

**Issue by physedo** [socraticorg/mathsteps#218]
I am using mathsteps in a project. When I prepare the project for production. I get errors when I want t solve equations. Something is wrong getSymbolsInEquation see the issue below:
https://forum.ionicframework.com/t/error-ionic-cordova-run-android-device-prod/102569
Simplify expressions in the project works fine.

If I skip minifyjs everything works fine when I serve the application in the browser

**Comment by evykassirer** [comment]
very strange - I have no idea what that's happening but I replied to the thread and hopefully someone can help us figure it out :) thanks for bringing it to my attention!

**Comment by physedo** [comment]
Simplify expression is working. It was working in july. I have posted My
code in The ionicforum. I have no idea what is wrong.



Den 30 aug. 2017 01:05 skrev "Evy Kassirer" <notifications@github.com>:

**Comment by physedo** [comment]
There is no Bug. It was the ionic. It works now. mathsteps rocks @evykassirer

**Comment by evykassirer** [comment]
phew! thanks for checking back and so glad it works now! :)
