### ISSUE TITLE
Functions step.oldEquation.ascii() and step.newEquation.ascii() not working.

### ISSUE THREAD

**Issue by Flashomatic** [socraticorg/mathsteps#226]
I can not figure out how to convert the equations into text, because these functions don't work despite being in the docs.

**Comment by evykassirer** [comment]
oh no :( 

How are you using mathsteps? Did you npm install it or fork the code?

**Comment by Flashomatic** [comment]
I npm installed it.

**Comment by evykassirer** [comment]
OH we updated the README when we changed `print` to `ascii` but haven't done an npm release since then. Use print instead, or use the new version (will be updating it tonight)

I'll update the README to mention both! thanks for pointing this out!

**Comment by evykassirer** [comment]
lemme know if it works :)

**Comment by Flashomatic** [comment]
It works fine now. Thank you.
