### ISSUE TITLE
Quadratic Equations Not Working

### ISSUE THREAD

**Issue by Flashomatic** [socraticorg/mathsteps#227]
When I have mathsteps solve a quadratic equation , such as x^2-5x+6=0, it gets to x^2-5x=-6 and then says the equation is solved, even though it solved for x^2-5x instead of x.

**Comment by Flashomatic** [comment]
Never Mind, I had an outdated version of mathsteps.

**Comment by evykassirer** [comment]
Glad we updated a thing you needed! Awesome :)
