### ISSUE TITLE
Write a git pre-commit hook to run tests and lint

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#30]
A pre-commit hook runs the tests and linter before someone commits, which will help prevent buggy/un-linted code from even getting into a commit.

The tests that need to be run: `npm test`
The linter: `npm run lint`

Here are some articles I found that talk a bit about this (I don't know much about it though):
- http://githooks.com/
- http://codeinthehole.com/writing/tips-for-using-a-git-pre-commit-hook/
- http://www.mokacoding.com/blog/pre-commit-hooks/

**Comment by evykassirer** [comment]
thans @hmaurer !!

**Comment by sterlingw** [comment]
Came across this when googling to setup precommit/prepush githooks. I understand that you all solved this, but hopefully this is helpful for future reference 😄 

Not sure if you all have seen this: https://github.com/typicode/husky - but all that it took was installing `husky` and adding `"prepush": "yarn lint && yarn test"` to the package.json scripts to setup a prepush githook. No modifying of .git or bash scripts necessary.
