### ISSUE TITLE
Add an optional parameter to isOperator to check the operation type

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#31]
there are some places in the codebase where you'll see

`if (NodeType.isOperator(node) && node.op === '+') { `

it would be nice if `isOperator` took an optional argument to check op at the same time, so we could change the above snippet to

`if (NodeType.isOperator(node, '+') {`

and then any `if (NodeType.isOperator(node) && node.op === ... ` can be replaced in the codebase

**Comment by mcarthurgill** [comment]
I've made these changes, but I believe I need you to assign this issue to me. Thanks!

**Comment by evykassirer** [comment]
Thanks! :tada:  

Hmmm either I need to be given higher permissions for this repo (I didn't create it) or I might not be able to assign you at all... looking into it :)

In the mean time consider this conversation to show that you've 'claimed' this issue, feel free to open a PR with your change and I'll take a look

**Comment by evykassirer** [comment]
@mcarthurgill you said you've made the changes - can you open a pull request so they can be merged?

**Comment by mcarthurgill** [comment]
Done! Let me know if you have questions.

**Comment by evykassirer** [comment]
Thanks @mcarthurgill ! 

Feel free to take a look at other open issues, and lemme know if I can help with anything.
