### ISSUE TITLE
Make a helper function getRadicandNode

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#34]
e.g. cuberoot(5) is represented in mathjs as nthRoot(5, 3) and it has root 3 and radicand 5

there's an existing function `getRootNode` which is a helper function for the getting the root number 

but then you see:

```
const radicandNode = node.args[0];
const rootNode = getRootNode(node);
```

It'd be nice to use a `getRadicandNode(node)`  function which returns `node.args[0];` 
(that's it! a great small first change)

**Comment by lexiross** [comment]
I can do this one!

**Comment by evykassirer** [comment]
done! Thanks @lexiross 🎉
