### ISSUE TITLE
Make a TestUtil to reduce repeated code in tests

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#42]
Almost every test has the same structure. To test before -> after:
- parse the 'before' string
- flatten it to the structure we use for mathsteps
- call the function we're testing
- assert that the printed result is the same as the 'after' string

e.g. here are two real test function in the code right now

```
function testArithmetic(exprStr, outputStr) {
  it(exprStr + ' -> ' + outputStr, function () {
    assert.deepEqual(
      print(evaluateArithmetic(flatten(math.parse(exprStr))).newNode),
      outputStr);
  });
}

function testSimplify(exprStr, outputStr) {
  it(exprStr + ' -> ' + outputStr, function () {
    assert.deepEqual(
      print(simplifyBasics(flatten(math.parse(exprStr))).newNode),
      outputStr);
  });
}
```

We should make a TestUtil to reduce copying this structure around everywhere (i.e. the code [DRY](http://deviq.com/don-t-repeat-yourself/)).

So the `testArithmetic` could look something like:

```
function testArithmetic(originalStr, expectedOutputStr) {
    TestUtil.testSimplification(evaluateArithmetic, originalStr, expectedOutputStr);
}
```

and then we could do a similar for one testing substeps (which also shows up in a bunch of places in the code - adding constant fractions is a good example)

**Comment by evykassirer** [comment]
Marking this as small because I don't think you have to know much about the code to do this, but it does touch a lot of code so in that sense it's not that small.

**Comment by nitin42** [comment]
Can I be assigned for this?

**Comment by evykassirer** [comment]
Yes! Thanks :)

**Comment by nitin42** [comment]
Work in progress just wanted to confirm that this is how the blueprint would look like for the util functions after reducing the code in tests : 

```javascript
'use strict';
const {canSimplifyPolynomialTerms} = require('../../lib/checks');
const {simplifyPolynomial} = require('../TestUtil');

function testCanCombine(exprStr, canCombine) {
  simplifyPolynomial(canSimplifyPolynomialTerms, exprStr, canCombine);
}

describe('canSimplifyPolynomialTerms multiplication', function() {
  const tests = [
    ['x^2 * x * x', true],
    // false b/c coefficient
    ['x^2 * 3x * x', false],
    ['y * y^3', true],
    ['5 * y^3', false], // just needs flattening
    ['5/7 * x', false], // just needs flattening
    ['5/7 * 9 * x', false],
  ];
  tests.forEach(t => testCanCombine(t[0], t[1]));
});
```
This also eliminates the additional imports in all the test files. Placing all of them in a single util file For eg - 
```javascript
require('assert');
require('math');
require('print');
require('flatten');
```

This would help me in writing the better and neat test. I am also using destructuring assignments wherever necessary.

**Comment by evykassirer** [comment]
`testCanCombine` is a little different because it's not comparing nodes/strings, it's checking true/false. I think you should probably leave that test the way it is for now, or come up with a general function that would be used like:

```js
function testCanCombine(exprStr, canCombine) {
  TestUtil.testBooleanFunction(canSimplifyPolynomialTerms, exprStr, canCombine);
}
```

(not sure if `testBooleanFunction` is the best name, but it's all I could think of right now)

----

for substeps, I'd expect:

```js
function testCollectAndCombineSubsteps(exprString, outputList, outputStr) {
  TestUtil.testSubsteps(collectAndCombineSearch, exprString, outputList, outputStr);
}
```

----

I think it'd be best if you put up your code in a pull request and we can talk about it there - will be easier to point out things :) 

---

>  Also that I have written the test coverage for other functions that are separated, should I merge them along?

That's awesome! That's related to an assigned issue #58, so I'd say put it up in a separate pull request from this change to add the `TestUtil` - make sense?

---

Let me know if you have any questions!

**Comment by nitin42** [comment]
I'll write a more general method for 
> I think you should probably leave that test the way it is for now, or come up with a general function that would be used like:

Right now I am clearing my messy code. But soon it will be up for the PR. 

> That's awesome! That's related to an assigned issue #58, so I'd say put it up in a separate pull request from this change to add the TestUtil - make sense?

Your point is valid.

**Comment by evykassirer** [comment]
sounds good. looking forward to the PR!

**Comment by evykassirer** [comment]
done! thanks so much @nitin42
