### ISSUE TITLE
Improve our linter

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#44]
here's a list of things I'd like to add to `.eslintrc.js`

note: feel free to take on this issue an only add some of the rules and not all of them.

(comment below if you have more suggestions!)

- [x] use `const` in every place it can be used
- [x] never use `==`
- [x] 2 spaces for indentation, no tabs
- [x] no trailing spaces at the end of lines
- [x] http://eslint.org/docs/rules/object-shorthand
- [ ] http://eslint.org/docs/rules/brace-style stroustrup
- [ ] alphabetize `require` statements at top of files
- [ ] make sure we also have the `'use strict'` line
- [x] only use single quotes, no double quotes
- [x] no lines ending in white space
- [ ] space after keywords http://eslint.org/docs/rules/keyword-spacing

**Comment by biyasbasak** [comment]
I am working on this

**Comment by evykassirer** [comment]
woo! thanks @biyasbasak

**Comment by Raibaz** [comment]
Is it still open and assignable? I can add the missing rules if needed.

**Comment by evykassirer** [comment]
yes please! thank you :)

**Comment by Raibaz** [comment]
I opened PR #107 about this, but I have some doubts about the `'use strict'` line: if I enable the [strict rule](http://eslint.org/docs/rules/strict), linting gives errors on almost every file since `use strict' is unnecessary inside of modules`, since ES6 modules are strict by default.

How do you think we should handle this?

**Comment by evykassirer** [comment]
oh! I didn't realize it's strict by default. Let's get rid of `"use strict";` in those files then. Thanks :D

**Comment by evykassirer** [comment]
done!! until we find more rules we want to add haha.

but let's close this for now :)

thanks so much @biyasbasak and @Raibaz for making the mode more beautiful 😍
