### ISSUE TITLE
publish npm module

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#61]
@aelnaiem can I do this now that the file reorg is pretty much done?

- [x] make an npm account for Socratic
 - username: `@socratic`
 - email: `mathsteps@socratic.org`
- [x] `npm publish`
- [x] update README with installation instructions

If you'd rather do it, that's fine! We can discuss on this github issue

**Comment by aelnaiem** [comment]
@evykassirer Yes you can do this!
