### ISSUE TITLE
separate basicsSearch simplifications into their own files

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#62]
there's a bunch of little simplifications in `basicsSearch`:

(at the time of writing this issue:)
```
  // multiplication by 0 yields 0
  reduceMultiplicationByZero,
  // division of 0 by something yields 0
  reduceZeroDividedByAnything,
  // ____^0 --> 1
  reduceExponentByZero,
  // Check for x^1 which should be reduced to x
  removeExponentByOne,
  // - - becomes +
  simplifyDoubleUnaryMinus,
  // If this is a + node and one of the operands is 0, get rid of the 0
  removeAdditionOfZero,
  // If this is a * node and one of the operands is 1, get rid of the 1
  removeMultiplicationByOne,
  // In some cases, remove multiplying by -1
  removeMultiplicationByNegativeOne,
  // If this is a / node and the denominator is 1 or -1, get rid of it
  removeDivisionByOne,
  // e.g. x*5 -> 5x
  rearrangeCoefficient,
```

`reduceMultiplicationByZero`,  `reduceZeroDividedByAnything`, and `rearrangeCoefficient` are defined and tested their own files, and ideally all of the functions would each be in their own file with their own small set of unit tests. This change is just moving the code around - a great first PR!

**Comment by Raibaz** [comment]
Hi, i started working on this but i can't seem to be able to assign it to myself...what should i do?

**Comment by evykassirer** [comment]
Just commenting here works - I'll look into it in the meantime. Thanks for taking this on!!

**Comment by evykassirer** [comment]
Hm, okay turns out I can't actually assign just anyone to issues (only people who have been added on GitHub as contributors) I'll change the contributing.md and also take a look at your PR now :)

**Comment by evykassirer** [comment]
Ooo -- unfortunately, this change conflicts a bit with #69 cause they're both in `simplifyBasics`, so one of you will have to merge in the other's change eventually :imp:

**Comment by evykassirer** [comment]
done! thanks @Raibaz 🎉
