### ISSUE TITLE
Example video is restricted

### ISSUE THREAD

**Issue by emilingerslev** [socraticorg/mathsteps#71]
The example video seems to be restricted to a set of countries. At least it is not allowed to be shown in Denmark.
That, I guess, is a mistake?

**Comment by pubkey** [comment]
Same in Germany :-1:

**Comment by bali182** [comment]
Same in Ireland

**Comment by pubkey** [comment]
Ok I found out that the linked youtube-video shows the song "Step By Step" from "New Kids On The Block".

![screenshot from 2017-01-20 11-33-23](https://cloud.githubusercontent.com/assets/8926560/22146299/773d5eee-df04-11e6-855d-5784e906cfac.png)

**Comment by bali182** [comment]
Awesome... :man_dancing:

**Comment by evykassirer** [comment]
Oh no! It was just a silly joke video (Step by Step, by the New Kids on the Block) - didn't realize it was restricted in so many places.

I'm replacing with https://www.youtube.com/watch?v=iCrargw1rrM which seems to be available everywhere. Closing this issue, but if you still have trouble with the new link please reopen.
