### ISSUE TITLE
Youtube's video unavailable in Russia. Math for everyone...

### ISSUE THREAD

**Issue by 3cL1p5e7** [socraticorg/mathsteps#73]

**Comment by hmaurer** [comment]
c.f. https://github.com/socraticorg/mathsteps/issues/71

**Comment by evykassirer** [comment]
Sorry! I'm replacing with https://www.youtube.com/watch?v=iCrargw1rrM which seems to be available everywhere.

Check out #71 for more details (thanks @hmaurer)
