### ISSUE TITLE
Use object literal property value shorthand in es6

### ISSUE THREAD

**Issue by cspanda** [socraticorg/mathsteps#80]
Instead of doing something like this inside /index.js:

```javascript

const simplifyExpression = require('./lib/simplifyExpression');
const solveEquation = require('./lib/solveEquation');
const ChangeTypes = require('./lib/ChangeTypes');

module.exports = {
  simplifyExpression: simplifyExpression,
  solveEquation: solveEquation,
  ChangeTypes: ChangeTypes,
};
```
follow airbnb's [style guide](https://github.com/airbnb/javascript/blob/master/README.md#es6-object-concise) and use object literal property value shorthand in es6 so it becomes shorter and more readable. 

```javascript
const simplifyExpression = require('./lib/simplifyExpression');
const solveEquation = require('./lib/solveEquation');
const ChangeTypes = require('./lib/ChangeTypes');

module.exports = {
  simplifyExpression,
  solveEquation,
  ChangeTypes,
};
```

**Comment by evykassirer** [comment]
Woo thanks for making an issue for this ^_^ 

A great addition to the 'small' label (which is good, cause we're running low on them)

**Comment by evykassirer** [comment]
cool, this shorthand is also supported by eslint (which we use): http://eslint.org/docs/rules/object-shorthand

I'll add it to the linter error issue too ( #44 )

**Comment by evykassirer** [comment]
done! thanks @cspanda -- so speeedy 🐰🐇
