### ISSUE TITLE
make it clear that mathsteps requires node 6.0.0 

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#82]
`mathsteps` won't work with lower versions of node (e.g. #77), so we should add this requirement to the README

ideally this bullet point would link to a good resource for installing/updating node

**Comment by emars** [comment]
If this is a recurring issue, something like:

http://stackoverflow.com/a/41620850/2816843

could be implemented.

Having a `preinstall` check that verifies that the user is on the proper version of node.

**Comment by evykassirer** [comment]
oh, sweet! 

that looks very helpful and I totally think we should add it, thanks :)

**Comment by Raibaz** [comment]
Nice one @emars :)

**Comment by evykassirer** [comment]
script done! thanks to @Raibaz and to @emars for the suggestion

**Comment by evykassirer** [comment]
there's an issue where if you `npm install mathsteps` there's an error `Error: Cannot find module 'semver'
`

I don't have time to look into it now, but hopefully we can fix it soon. 

@aelnaiem ?

**Comment by Raibaz** [comment]
I think this is because `preinstall` is run before dependencies are installed...perhaps moving `npm run requirements-check` to `install` or `postinstall` would fix it?

**Comment by evykassirer** [comment]
yeah I think that's the issue too.. it's odd because both the stackoverflow answer and medium post user `preinstall` but then dependencies aren't installed yet :p so maybe they're wrong!

I'm also looking around to try to find ways to test installing it again without patching a new version. Let me know if you know of anything

**Comment by aelnaiem** [comment]
It seems that node-semver should be installed with npm according to this:
https://docs.npmjs.com/files/package.json

**Comment by aelnaiem** [comment]
Enforcing the engine [was deprecated](https://github.com/npm/npm/blob/master/CHANGELOG.md#enginestrict) as part of an effort to shift control from module authors to application authors. Curious if this suggests that the best practice is to just notify application authors of the node version requirement in the README, and they can also see the requirement in the package.json

**Comment by evykassirer** [comment]
Sounds OK to me - too bad though :(

**Comment by evykassirer** [comment]
should be fixed now :)
