### ISSUE TITLE
Idea: create a RESOURCES.md

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#95]
This would have a list of similar apps/projects (to use for examples) and also point out relevant research papers for anyone interested in learning more about this stuff.

Would this be helpful to people?

**Comment by tkosan** [comment]
I think having a resource document like this would be very helpful. One open source application that I think would qualify for the list is a step-by-step equation solver that I have been working on for the past few years. Here is a video demonstration of it:

[Solver with tree interface](https://www.youtube.com/watch?v=cy6bwNBkAK0)

I am hoping to implement some of the capabilities of this equation solver into mathsteps. I also accumulated a significant number of research papers that my equation solver is based on that I would like to add to this resource.

**Comment by evykassirer** [comment]
Awesome @tkosan ! I'll start off the resources file and you can make a pull request to add to it :)

Where is your open source code available to look at? I'd love to see what you've been doing.

I would be very grateful if you could bring what you've learned form mathpiper to mathsteps 😃  looking forward to your contributions!

**Comment by evykassirer** [comment]
I think @sangwinc would have some great stuff for this file too

**Comment by tkosan** [comment]
Chris Sangwin was the person who inspired me to create the MathPiper step-by-step equation solver.

Here is a link to the main files that contain the solver (SolveSteps.mpws) and the rules that the solver and the manual manipulator use (rulebase_elementary_algebra.mpws):

[Solver and rules](https://bitbucket.org/tkosan/mathpiperide/src/67c8b031230bc3fcd9776700487b570ebe62717b/src/library_apps/mathpiper4/src/org/mathpiper/scripts4/steps/?at=master)

If you would like to play with the solver and manipulator let me know, and I will put up instructions on how to use them somewhere.

When I read your blog post about mathsteps, I was very excited to see that you utilized expression trees to explain how the math was working. This is an approach that research indicates is very promising for math education:

[Structure in algebra research paper](http://pat-thompson.net/PDFversions/1987StrucInAlg.pdf)

This research paper inspired me to create the following expression tree structure explorer application:

[Expression tree structure app](http://patternmatics.org/test/expression_structure.html)

**Comment by evykassirer** [comment]
Done! Feel free to add more to it :)
