### ISSUE TITLE
Create a section in README for API docs or put em in Wiki section

### ISSUE THREAD

**Issue by karuppiah7890** [socraticorg/mathsteps#98]
I didn't know how to use the `mathsteps.solveEquation()` function. And the README is misleading, as if we just have to change `mathsteps.simplifyExpression()` to `mathsteps.solveEquation()` to solve an equation. Finally I had to see some tests and understand how to use the API and ended up coding this small piece of code to see how the lib works 

```javascript
const mathsteps = require('mathsteps');

const steps = mathsteps.solveEquation('2x + 3x = 35');

console.log(steps[steps.length-1].newEquation.print());
```

I personally feel there should be documentation on API usage

**Comment by evykassirer** [comment]
Very much agreed! It should go in the README.

I'll try to get this done this weekend, or you could add it if you're interested :)

**Comment by evykassirer** [comment]
(let me know if you want to do it and I'll leave it to you)

**Comment by karuppiah7890** [comment]
I am new to the repository. I need some guidance on this. And it's API documentation, I think people who created the API should do it, or help me do it. But the latter is kind of double work in this case, no ?

**Comment by evykassirer** [comment]
I don't mind double work if you're interested in working on it (always happy to support someone contributing to `mathsteps`!) but am also quite fine to do it on my own - just wanted to give you the option :)

**Comment by karuppiah7890** [comment]
Okay! Let me help :smile:

**Comment by karuppiah7890** [comment]
We can discuss here or in gitter.im and I am in India, UTC+05:30 time zone.

**Comment by karuppiah7890** [comment]
It's night now, for me. We can discuss tomorrow!

**Comment by evykassirer** [comment]
goodnight! 🌃 

oo I was going to make a gitter for mathsteps! I'm so glad you suggested it too.

I'm thinking something very similar to the existing expression example in the README, just add one for equations

e.g. building on your example above

```js
const mathsteps = require('.');

const steps = mathsteps.solveEquation('2x + 3x = 35');

console.log(steps);
steps.forEach(step => {
	// e.g. before change: 2x + 3x = 35
    console.log("before change: " + step.oldEquation.print());
    // e.g. change: SIMPLIFY_LEFT_SIDE
    console.log("change: " + step.changeType);
    // e.g. after change: 5x = 35
    console.log("after change: " + step.newEquation.print());
    // e.g. # of substeps: 2
    console.log("# of substeps: " + step.substeps.length);
});
```

what do you think?

**Comment by karuppiah7890** [comment]
Pretty neat code! @evykassirer :smile:

**Comment by karuppiah7890** [comment]
Do add this one as an example for equations ! :smile: Just remove the `console.log(steps)` line since it puts up lots of clumsy values. The `forEach` function part shows em in a neat manner.

**Comment by evykassirer** [comment]
oh yes! I meant to take that line out oooops.

Do you want to make the pull request that adds this example?

**Comment by karuppiah7890** [comment]
Sure! :+1:

**Comment by karuppiah7890** [comment]
I created a separate issue for the equation solving example. #102 And created a PR #103 for the same

**Comment by evykassirer** [comment]
great! would you like to see more thorough API docs too? or do you think the example you added gives enough information (which would mean we can close this issue)

**Comment by evykassirer** [comment]
sweet, I think it should go in the wiki #66

**Comment by karuppiah7890** [comment]
Cool, so shall we close this issue ? or just keep it open till we add docs Wiki ?

And woah, Wiki has lots of stuff, that can help contributors to get familiar with the code base :+1: and contribute with more ease!

**Comment by evykassirer** [comment]
eh, let's just close this issue, and have it part of the wiki issue instead.

yeah! I'm excited about the wiki 👍
